### ISSUE TITLE
Support for other stores

### ISSUE THREAD

**Issue by umaar** [dexaai/dexter#24] opened 2024-02-13 12:21 UTC
Hey do you plan to provide support for other data stores? A free one that could be self hosted would be nice.

**Comment by rileytomasek** [comment] 2024-02-13 14:45
The [Pinecone implementation](https://github.com/dexaai/dexter/tree/master/src/datastore/pinecone) extends `AbstractDatastore`. We're open to PRs that follow the same pattern for different providers.

**Comment by rileytomasek** [comment] 2024-02-13 14:47
Closing this as a duplicate of #12

**Closed by rileytomasek** 2024-02-13 14:47 UTC
